### ISSUE TITLE
information on weights used in load_weights

### ISSUE THREAD

**Issue by vishalghor** [Golbstein/EDSR-Keras#1]
Hi @Golbstein ,

I was looking at your code for study purpose, it would be very helpful if you could tell me about the pretrained weights which you had loaded in the jupyter network. if possible can you share the pretrained weights.

Thanks and Regards
Vishal

**Comment by Golbstein** [comment]
Unfortunately I don't have them. However, you can train this model by yourself pretty quick. I got good results within 1 hour of training on 1 - 1080Ti GPU

**Comment by vishalghor** [comment]
@Golbstein thank you.
